#loc = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":46:1)
#map = affine_map<(d0) -> (d0)>
#set = affine_set<(d0)[s0] : (d0 >= 0, -d0 + s0 - 1 >= 0)>
#set1 = affine_set<(d0) : (d0 >= 0, -d0 + 63 >= 0)>
#loc11 = loc("a_ptr"(#loc))
#loc12 = loc("b_ptr"(#loc))
#loc13 = loc("c_ptr"(#loc))
#loc14 = loc("n"(#loc))
module {
  tt.func public @vector_add_kernel(%a_ptr: !tt.ptr<f16> loc("a_ptr"(#loc)), %b_ptr: !tt.ptr<f16> loc("b_ptr"(#loc)), %c_ptr: !tt.ptr<f16> loc("c_ptr"(#loc)), %n: i32 loc("n"(#loc))) attributes {noinline = false} {
    %pid = arith.constant 32 : index loc(#loc15)
    %pid_0 = arith.constant 16 : index loc(#loc15)
    %c64_i32 = arith.constant 64 : i32 loc(#loc2)
    %pid_1 = ktdp.get_compute_tile_id : index loc(#loc15)
    scf.for %pid_2 = %pid_1 to %pid_0 step %pid {
      ktdf.corelet_plan pattern = "single_corelet" {
        ktdf.corelet 0 {data_bounds = [0, 1]} loc(#loc15)
      } loc(#loc15)
      %pid_3 = arith.index_cast %pid_2 : index to i32 loc(#loc15)
      %offset = arith.muli %pid_3, %c64_i32 : i32 loc(#loc16)
      %a_desc = builtin.unrealized_conversion_cast %a_ptr : !tt.ptr<f16> to index loc(#loc17)
      %a_desc_4 = arith.index_cast %n : i32 to index loc(#loc17)
      %a_desc_5 = ktdp.construct_memory_view %a_desc, sizes: [%a_desc_4], strides: [1] {coordinate_set = #set, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<?xf16> loc(#loc17)
      %b_desc = builtin.unrealized_conversion_cast %b_ptr : !tt.ptr<f16> to index loc(#loc18)
      %b_desc_6 = arith.index_cast %n : i32 to index loc(#loc18)
      %b_desc_7 = ktdp.construct_memory_view %b_desc, sizes: [%b_desc_6], strides: [1] {coordinate_set = #set, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<?xf16> loc(#loc18)
      %c_desc = builtin.unrealized_conversion_cast %c_ptr : !tt.ptr<f16> to index loc(#loc19)
      %c_desc_8 = arith.index_cast %n : i32 to index loc(#loc19)
      %c_desc_9 = ktdp.construct_memory_view %c_desc, sizes: [%c_desc_8], strides: [1] {coordinate_set = #set, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<?xf16> loc(#loc19)
      %a = arith.index_cast %offset : i32 to index loc(#loc20)
      %a_10 = ktdp.construct_access_tile %a_desc_5[%a] {access_tile_order = #map, access_tile_set = #set1} : memref<?xf16> -> !ktdp.access_tile<64xindex> loc(#loc20)
      %a_11 = ktdp.load %a_10 : <64xindex> -> tensor<64xf16> loc(#loc20)
      %b = arith.index_cast %offset : i32 to index loc(#loc21)
      %b_12 = ktdp.construct_access_tile %b_desc_7[%b] {access_tile_order = #map, access_tile_set = #set1} : memref<?xf16> -> !ktdp.access_tile<64xindex> loc(#loc21)
      %b_13 = ktdp.load %b_12 : <64xindex> -> tensor<64xf16> loc(#loc21)
      %0 = arith.addf %a_11, %b_13 : tensor<64xf16> loc(#loc9)
      %1 = arith.index_cast %offset : i32 to index loc(#loc10)
      %2 = ktdp.construct_access_tile %c_desc_9[%1] {access_tile_order = #map, access_tile_set = #set1} : memref<?xf16> -> !ktdp.access_tile<64xindex> loc(#loc10)
      ktdp.store %0, %2 : tensor<64xf16>, <64xindex> loc(#loc10)
    } loc(#loc15)
    tt.return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":47:11)
#loc2 = loc(unknown)
#loc3 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":48:14)
#loc4 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":49:14)
#loc5 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":51:14)
#loc6 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":53:14)
#loc7 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":55:9)
#loc8 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":56:9)
#loc9 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":57:28)
#loc10 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/vector_add.py":57:5)
#loc15 = loc("pid"(#loc1))
#loc16 = loc("offset"(#loc3))
#loc17 = loc("a_desc"(#loc4))
#loc18 = loc("b_desc"(#loc5))
#loc19 = loc("c_desc"(#loc6))
#loc20 = loc("a"(#loc7))
#loc21 = loc("b"(#loc8))
