#loc = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":98:1)
#loc2 = loc(unknown)
#loc4 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":119:10)
#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0) -> (d0)>
#set = affine_set<(d0, d1) : (d0 >= 0, -d0 + 63 >= 0, d1 >= 0, -d1 + 4095 >= 0)>
#set1 = affine_set<(d0) : (d0 >= 0, -d0 + 4095 >= 0)>
#loc19 = loc("desc_x"(#loc))
#loc20 = loc("desc_w"(#loc))
#loc21 = loc("desc_o"(#loc))
#loc24 = loc("ms"(#loc4))
#loc34 = loc(callsite(#loc2 at #loc24))
module {
  tt.func public @rmsnorm_fwd(%desc_x: !tt.ptr<f16> loc("desc_x"(#loc)), %desc_w: !tt.ptr<f16> loc("desc_w"(#loc)), %desc_o: !tt.ptr<f16> loc("desc_o"(#loc))) attributes {noinline = false} {
    %start_m = arith.constant 32 : index loc(#loc22)
    %start_m_0 = arith.constant 1 : index loc(#loc22)
    %c0 = arith.constant 0 : index loc(#loc2)
    %r = arith.constant 1.001360e-05 : f16 loc(#loc23)
    %r_1 = tensor.splat %r : tensor<64xf16> loc(#loc23)
    %ms = arith.constant 2.441410e-04 : f16 loc(#loc24)
    %ms_2 = tensor.splat %ms : tensor<64xf16> loc(#loc24)
    %c64_i32 = arith.constant 64 : i32 loc(#loc2)
    %start_m_3 = ktdp.get_compute_tile_id : index loc(#loc22)
    scf.for %start_m_4 = %start_m_3 to %start_m_0 step %start_m {
      ktdf.corelet_plan pattern = "partial_combine" {
        ktdf.corelet 0 {data_bounds = [0, 2048], role = "partial", ring_send = "ccw"} loc(#loc22)
        ktdf.corelet 1 {data_bounds = [2048, 4096], role = "combine", ring_recv = "ccw"} loc(#loc22)
      } loc(#loc22)
      %start_m_5 = arith.index_cast %start_m_4 : index to i32 loc(#loc22)
      %x_desc = builtin.unrealized_conversion_cast %desc_x : !tt.ptr<f16> to index loc(#loc25)
      %x_desc_6 = ktdp.construct_memory_view %x_desc, sizes: [64, 4096], strides: [4096, 1] {coordinate_set = #set, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<64x4096xf16> loc(#loc25)
      %w_desc = builtin.unrealized_conversion_cast %desc_w : !tt.ptr<f16> to index loc(#loc26)
      %w_desc_7 = ktdp.construct_memory_view %w_desc, sizes: [4096], strides: [1] {coordinate_set = #set1, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<4096xf16> loc(#loc26)
      %o_desc = builtin.unrealized_conversion_cast %desc_o : !tt.ptr<f16> to index loc(#loc27)
      %o_desc_8 = ktdp.construct_memory_view %o_desc, sizes: [64, 4096], strides: [4096, 1] {coordinate_set = #set, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<64x4096xf16> loc(#loc27)
      %offs_m = arith.muli %start_m_5, %c64_i32 : i32 loc(#loc28)
      %x = arith.index_cast %offs_m : i32 to index loc(#loc29)
      %x_9 = ktdp.construct_access_tile %x_desc_6[%x, %c0] {access_tile_order = #map, access_tile_set = #set} : memref<64x4096xf16> -> !ktdp.access_tile<64x4096xindex> loc(#loc29)
      %x_10 = ktdp.load %x_9 : <64x4096xindex> -> tensor<64x4096xf16> loc(#loc29)
      %ms_11 = arith.mulf %x_10, %x_10 : tensor<64x4096xf16> loc(#loc30)
      %ms_12 = "tt.reduce"(%ms_11) <{axis = 1 : i32}> ({
      ^bb0(%ms_17: f16 loc(callsite(#loc2 at #loc24)), %ms_18: f16 loc(callsite(#loc2 at #loc24))):
        %ms_19 = arith.addf %ms_17, %ms_18 : f16 loc(#loc35)
        tt.reduce.return %ms_19 : f16 loc(#loc33)
      }) : (tensor<64x4096xf16>) -> tensor<64xf16> loc(#loc33)
      %ms_13 = arith.mulf %ms_12, %ms_2 : tensor<64xf16> loc(#loc24)
      %r_14 = arith.addf %ms_13, %r_1 : tensor<64xf16> loc(#loc23)
      %r_15 = math.rsqrt %r_14 : tensor<64xf16> loc(#loc31)
      %w = ktdp.construct_access_tile %w_desc_7[%c0] {access_tile_order = #map1, access_tile_set = #set1} : memref<4096xf16> -> !ktdp.access_tile<4096xindex> loc(#loc32)
      %w_16 = ktdp.load %w : <4096xindex> -> tensor<4096xf16> loc(#loc32)
      %0 = tt.expand_dims %r_15 {axis = 1 : i32} : tensor<64xf16> -> tensor<64x1xf16> loc(#loc15)
      %1 = tt.broadcast %0 : tensor<64x1xf16> -> tensor<64x4096xf16> loc(#loc16)
      %2 = arith.mulf %x_10, %1 : tensor<64x4096xf16> loc(#loc16)
      %3 = tt.expand_dims %w_16 {axis = 0 : i32} : tensor<4096xf16> -> tensor<1x4096xf16> loc(#loc17)
      %4 = tt.broadcast %3 : tensor<1x4096xf16> -> tensor<64x4096xf16> loc(#loc16)
      %5 = arith.mulf %2, %4 : tensor<64x4096xf16> loc(#loc16)
      %6 = arith.index_cast %offs_m : i32 to index loc(#loc18)
      %7 = ktdp.construct_access_tile %o_desc_8[%6, %c0] {access_tile_order = #map, access_tile_set = #set} : memref<64x4096xf16> -> !ktdp.access_tile<64x4096xindex> loc(#loc18)
      ktdp.store %5, %7 : tensor<64x4096xf16>, <64x4096xindex> loc(#loc18)
    } loc(#loc22)
    tt.return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":104:15)
#loc3 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":121:19)
#loc5 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":105:14)
#loc6 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":109:14)
#loc7 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":111:14)
#loc8 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":115:14)
#loc9 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":116:9)
#loc10 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":119:17)
#loc11 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/python/triton/language/standard.py":293:12)
#loc12 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/python/triton/language/standard.py":263:12)
#loc13 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":121:9)
#loc14 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":122:9)
#loc15 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":125:35)
#loc16 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":125:31)
#loc17 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":125:48)
#loc18 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rmsnorm.py":125:5)
#loc22 = loc("start_m"(#loc1))
#loc23 = loc("r"(#loc3))
#loc25 = loc("x_desc"(#loc5))
#loc26 = loc("w_desc"(#loc6))
#loc27 = loc("o_desc"(#loc7))
#loc28 = loc("offs_m"(#loc8))
#loc29 = loc("x"(#loc9))
#loc30 = loc("ms"(#loc10))
#loc31 = loc("r"(#loc13))
#loc32 = loc("w"(#loc14))
#loc33 = loc(callsite(#loc11 at #loc24))
#loc35 = loc(callsite(#loc12 at #loc33))
