#loc = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":131:1)
#map = affine_map<(d0, d1) -> (d0, d1)>
#set = affine_set<(d0, d1) : (d0 >= 0, -d0 + 8191 >= 0, d1 >= 0, -d1 + 127 >= 0)>
#set1 = affine_set<(d0, d1) : (d0 >= 0, -d0 + 255 >= 0, d1 >= 0, -d1 + 63 >= 0)>
#set2 = affine_set<(d0, d1) : (d0 >= 0, -d0 + 63 >= 0, d1 >= 0, -d1 + 63 >= 0)>
#loc19 = loc("desc_x"(#loc))
#loc20 = loc("desc_cos"(#loc))
#loc21 = loc("desc_sin"(#loc))
#loc22 = loc("desc_o"(#loc))
module {
  tt.func public @rope_fwd(%desc_x: !tt.ptr<f16> loc("desc_x"(#loc)), %desc_cos: !tt.ptr<f16> loc("desc_cos"(#loc)), %desc_sin: !tt.ptr<f16> loc("desc_sin"(#loc)), %desc_o: !tt.ptr<f16> loc("desc_o"(#loc))) attributes {noinline = false} {
    %c4 = arith.constant 4 : index loc(#loc1)
    %start_m = arith.constant 32 : index loc(#loc23)
    %start_m_0 = arith.constant 128 : index loc(#loc23)
    %c64 = arith.constant 64 : index loc(#loc1)
    %c0 = arith.constant 0 : index loc(#loc1)
    %c64_i32 = arith.constant 64 : i32 loc(#loc1)
    %c256_i32 = arith.constant 256 : i32 loc(#loc1)
    %start_m_1 = ktdp.get_compute_tile_id : index loc(#loc23)
    scf.for %start_m_2 = %start_m_1 to %start_m_0 step %start_m {
      ktdf.corelet_plan pattern = "split" {
        ktdf.corelet 0 {data_bounds = [0, 32]} loc(#loc23)
        ktdf.corelet 1 {data_bounds = [32, 64]} loc(#loc23)
      } loc(#loc23)
      %start_m_3 = arith.remui %start_m_2, %c4 : index loc(#loc23)
      %start_m_4 = arith.index_cast %start_m_3 : index to i32 loc(#loc23)
      %start_m_5 = arith.divui %start_m_2, %c4 : index loc(#loc23)
      %start_m_6 = arith.index_cast %start_m_5 : index to i32 loc(#loc23)
      %x_desc = builtin.unrealized_conversion_cast %desc_x : !tt.ptr<f16> to index loc(#loc24)
      %x_desc_7 = ktdp.construct_memory_view %x_desc, sizes: [8192, 128], strides: [128, 1] {coordinate_set = #set, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<8192x128xf16> loc(#loc24)
      %cos_desc = builtin.unrealized_conversion_cast %desc_cos : !tt.ptr<f16> to index loc(#loc25)
      %cos_desc_8 = ktdp.construct_memory_view %cos_desc, sizes: [256, 64], strides: [64, 1] {coordinate_set = #set1, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<256x64xf16> loc(#loc25)
      %sin_desc = builtin.unrealized_conversion_cast %desc_sin : !tt.ptr<f16> to index loc(#loc26)
      %sin_desc_9 = ktdp.construct_memory_view %sin_desc, sizes: [256, 64], strides: [64, 1] {coordinate_set = #set1, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<256x64xf16> loc(#loc26)
      %o_desc = builtin.unrealized_conversion_cast %desc_o : !tt.ptr<f16> to index loc(#loc27)
      %o_desc_10 = ktdp.construct_memory_view %o_desc, sizes: [8192, 128], strides: [128, 1] {coordinate_set = #set, memory_space = #ktdp.spyre_memory_space<HBM>} : memref<8192x128xf16> loc(#loc27)
      %offs_m = arith.muli %start_m_6, %c256_i32 : i32 loc(#loc28)
      %offs_m_11 = arith.muli %start_m_4, %c64_i32 : i32 loc(#loc29)
      %offs_m_12 = arith.addi %offs_m, %offs_m_11 : i32 loc(#loc28)
      %x1 = arith.index_cast %offs_m_12 : i32 to index loc(#loc30)
      %x1_13 = ktdp.construct_access_tile %x_desc_7[%x1, %c0] {access_tile_order = #map, access_tile_set = #set2} : memref<8192x128xf16> -> !ktdp.access_tile<64x64xindex> loc(#loc30)
      %x1_14 = ktdp.load %x1_13 : <64x64xindex> -> tensor<64x64xf16> loc(#loc30)
      %x2 = arith.index_cast %offs_m_12 : i32 to index loc(#loc31)
      %x2_15 = ktdp.construct_access_tile %x_desc_7[%x2, %c64] {access_tile_order = #map, access_tile_set = #set2} : memref<8192x128xf16> -> !ktdp.access_tile<64x64xindex> loc(#loc31)
      %x2_16 = ktdp.load %x2_15 : <64x64xindex> -> tensor<64x64xf16> loc(#loc31)
      %c = arith.index_cast %offs_m_11 : i32 to index loc(#loc32)
      %c_17 = ktdp.construct_access_tile %cos_desc_8[%c, %c0] {access_tile_order = #map, access_tile_set = #set2} : memref<256x64xf16> -> !ktdp.access_tile<64x64xindex> loc(#loc32)
      %c_18 = ktdp.load %c_17 : <64x64xindex> -> tensor<64x64xf16> loc(#loc32)
      %s = arith.index_cast %offs_m_11 : i32 to index loc(#loc33)
      %s_19 = ktdp.construct_access_tile %sin_desc_9[%s, %c0] {access_tile_order = #map, access_tile_set = #set2} : memref<256x64xf16> -> !ktdp.access_tile<64x64xindex> loc(#loc33)
      %s_20 = ktdp.load %s_19 : <64x64xindex> -> tensor<64x64xf16> loc(#loc33)
      %0 = arith.mulf %x1_14, %c_18 : tensor<64x64xf16> loc(#loc13)
      %1 = arith.mulf %x2_16, %s_20 : tensor<64x64xf16> loc(#loc14)
      %2 = arith.subf %0, %1 : tensor<64x64xf16> loc(#loc13)
      %3 = arith.index_cast %offs_m_12 : i32 to index loc(#loc15)
      %4 = ktdp.construct_access_tile %o_desc_10[%3, %c0] {access_tile_order = #map, access_tile_set = #set2} : memref<8192x128xf16> -> !ktdp.access_tile<64x64xindex> loc(#loc15)
      ktdp.store %2, %4 : tensor<64x64xf16>, <64x64xindex> loc(#loc15)
      %5 = arith.mulf %x2_16, %c_18 : tensor<64x64xf16> loc(#loc16)
      %6 = arith.mulf %x1_14, %s_20 : tensor<64x64xf16> loc(#loc17)
      %7 = arith.addf %5, %6 : tensor<64x64xf16> loc(#loc16)
      %8 = arith.index_cast %offs_m_12 : i32 to index loc(#loc18)
      %9 = ktdp.construct_access_tile %o_desc_10[%8, %c64] {access_tile_order = #map, access_tile_set = #set2} : memref<8192x128xf16> -> !ktdp.access_tile<64x64xindex> loc(#loc18)
      ktdp.store %7, %9 : tensor<64x64xf16>, <64x64xindex> loc(#loc18)
    } loc(#loc23)
    tt.return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":138:15)
#loc3 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":144:14)
#loc4 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":148:16)
#loc5 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":151:16)
#loc6 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":154:14)
#loc7 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":159:14)
#loc8 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":159:30)
#loc9 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":162:10)
#loc10 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":163:10)
#loc11 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":164:9)
#loc12 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":165:9)
#loc13 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":168:31)
#loc14 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":168:40)
#loc15 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":168:5)
#loc16 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":169:34)
#loc17 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":169:43)
#loc18 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":169:5)
#loc23 = loc("start_m"(#loc2))
#loc24 = loc("x_desc"(#loc3))
#loc25 = loc("cos_desc"(#loc4))
#loc26 = loc("sin_desc"(#loc5))
#loc27 = loc("o_desc"(#loc6))
#loc28 = loc("offs_m"(#loc7))
#loc29 = loc("offs_m"(#loc8))
#loc30 = loc("x1"(#loc9))
#loc31 = loc("x2"(#loc10))
#loc32 = loc("c"(#loc11))
#loc33 = loc("s"(#loc12))
