// SPDX-License-Identifier: Apache-2.0
//! THE MODEL-GEOMETRY DOOR — the only part of the KTIR → SuperDSC lowering that stays on this side,
//! and the reason it stays is that it cannot cross.
//!
//! ⭐ THE LOWERING ITSELF IS [`ktir_superdsc::emit::lower_ktir_to_superdsc`]. What is left here is
//! the name-keyed dispatch ([`lower`]) plus the two arms that turn a model's head geometry into
//! CONST GENERICS: [`scratchy_subtile::model_geometry`]'s `with_config_attn_geometry` /
//! `with_config_head_dim`, whose match arms are GENERATED by that crate's `build.rs` from every
//! checked-in `crates/models/arch/*/configs/*.json`.
//!
//! ⛔ THAT ARM SET IS THE CONSUMER'S MODEL INVENTORY, SO A LEAF CRATE MUST NOT OWN IT. It cannot be
//! received as data either — the whole point is that the values become `const` parameters, i.e. a
//! MONOMORPHISATION site. So the crate exposes
//! [`attn_at`](ktir_superdsc::emit::lower_ktir_to_superdsc::attn_at)`::<NQH, NKVH, HD>` and
//! [`rope_at`](ktir_superdsc::emit::lower_ktir_to_superdsc::rope_at)`::<HD>` as public generic entry
//! points and THE CALLER CROSSES THE DOOR. A third-party KTIR producer instantiates them from its
//! own configs; every build-time refusal here (a geometry with no arm is a loud bake error citing
//! `geometry_sources()`) is unchanged.
//!
//! ⭐⭐ AND THAT IS ALSO WHY THE MODEL'S AND THE BUNDLE'S OWN FACTS LIVE HERE. [`BundleAttnParams`] is
//! `ibm/main`'s `lower_one_node` parameter set for the attention path — the head geometry and the
//! attention multiplier off `SubOp::AttnDecode`, the swept rung and the row kind off the walk — and it
//! is an ARGUMENT of [`lower`], not a record on the program. `AttnFacts` was that record, and it let
//! the emulator (which executes the ops) and the card (which read the record) compute different
//! attention; the leaf crate now reads the six operand identities and the resident capacity out of the
//! program itself (`attn_operands`) and takes these four from whoever crossed the door.
//!
//! ⛔ THE TWO NEWTYPES BELOW ARE THE ORPHAN RULE, NOT A DESIGN. `OnAttnGeometry`/`OnHeadDim` are
//! `scratchy-subtile`'s traits and `AttnAt`/`RopeAt` are `ktir-superdsc`'s structs — neither is
//! local, so the impls need a type of THIS crate's own to hang on. They carry no logic: each wraps
//! the crate's argument pack and hands it straight to the generic entry point.

use ktir_superdsc::emit::EmittedOp;
use ktir_superdsc::emit::lower_ktir_to_superdsc as lk;
use ktir_superdsc::emit::lower_ktir_to_superdsc::{
    Error, Region, attn_at, elementwise, err, lmlast, matmul_proven, regions, rmsnorm, rope_at,
    scalarmul, silumul, split_out,
};
use ktir_superdsc::ktir_node::{KtirNode, Program};
use ktir_superdsc::placement::BundleLayout;

/// ⭐⭐⭐ THE FOUR THINGS THE PROGRAM CANNOT STATE — `ibm/main`'s `lower_one_node` PARAMETERS, at the
/// site that now needs them.
///
/// main lowered each node during the tape walk, so it read these straight off what it had in hand:
/// the head geometry and the attention multiplier from `node.op`'s `SubOp::AttnDecode` payload (the
/// numbers the `#[forward]` macro parsed out of the model config), and `active_cap` /
/// `rows_are_requests` from its own walk parameters, threaded down from the ladder driver. This split
/// lowers per BUNDLE instead, one pass later, so the same four facts are stated for the bundle at the
/// same place they were read — and they are read ONCE, off the graph's own `AttnDecode` nodes, by
/// [`crate::lower_subtile_tape_to_ktir::attn_bundle_params`].
///
/// ⛔ THIS IS NOT A RECORD ON THE PROGRAM, AND THE DIFFERENCE IS THE WHOLE POINT. `AttnFacts` hung
/// eleven fields off [`KtirNode`], so information flowed `SubtileIR → AttnFacts → SuperDSC` past the
/// IR: a third-party producer could not fill it, and the emulator (which runs the ops) and the card
/// (which read the record) were not obliged to agree. Seven of those eleven are now read out of the
/// program by `attn_operands`; these four are ARGUMENTS of the call, one value per bundle, supplied by
/// the caller on THIS side of the geometry door — which is where model and bundle facts legitimately
/// live (see the module header). A Triton producer's caller states its own, from its own configs.
///
/// `None` for a bundle with no attention node: an attention program arriving without these is a build
/// error naming them, never a descriptor built on a default.
#[derive(Clone, Copy, Debug)]
pub struct BundleAttnParams {
    /// main's `SubOp::AttnDecode { geom }` — the model's head geometry, as the VALUE the two doors
    /// below turn into const generics.
    pub geom: ktir_superdsc::head_counts::ModelAttnGeometry,
    /// main's `lower_one_node(.., rows_are_requests, ..)`.
    pub rows_are_requests: bool,
}

// ══════════════════════════════════════════════════════════════════════════════════════════════
//  THE DISPATCH — by the node kind the producer wrote into the program's name.
// ══════════════════════════════════════════════════════════════════════════════════════════════

/// One KTIR program → the SuperDSC descriptors main's body for that node kind emits.
///
/// `quantized` is main's own per-BUNDLE fp8 activation-quantize dedup set, threaded exactly as its
/// tape walk threaded it: q/k/v read one rms output and gate/up another, so each distinct activation
/// is quantized once and the later matmuls emit only `matmulfp8` + dequant.
///
/// `attn_params` is [`BundleAttnParams`] — main's own remaining parameters, for the two bodies whose
/// device laws need a fact no program states.
pub fn lower(
    k: &KtirNode,
    sym_id_base: &mut i64,
    layout: Option<&BundleLayout>,
    quantized: &mut std::collections::HashSet<String>,
    attn_params: Option<BundleAttnParams>,
) -> Result<Vec<EmittedOp>, Error> {
    // The name is still the program's identity for the emulator (which keys functions by it) and for
    // the descriptor suffixes, so it is READ — but nothing is parsed out of it.
    let name = k.func.name;
    let r = regions(k)?;
    // ⭐⭐⭐ ON THE TYPE, NOT ON THE NAME. This was `match name.split('_').next()`, so a program's kind
    // was a substring the producer wrote and this side parsed back out — a typo was a runtime refusal
    // and a new kind fell through a `_` arm. `KtirNode::program` states it, so there is NO catch-all
    // here and a producer that gains a kind is an E0004 at this match.
    match k.program {
        // `&[]` IS THE DENSE PATH, AND IT IS ARGUMENT 4. The broadcast flag slice is per-operand and
        // is stated by the whole-function walk from the region it read; a per-`Program` op has no
        // region to state one, and an empty slice is the byte-identical no-broadcast emission this
        // door always had. Measured: granite's baked descriptors are unchanged with this argument in
        // place, 2b and 8b at fp16 and fp8, `diff -r` 0 lines.
        //
        // ⛔ THE POSITION MATTERS AND THE COMPILER ONLY HALF-NAMES IT. `&[]` infers its element type
        // from whichever parameter it lands on, so writing it in slot 3 type-checks AS THE REGION LIST
        // and pushes the error onto the NEXT argument — `expected &[Option<BcastAxis>], found
        // &Vec<Region>` at `&r` — which reads as a problem with the regions rather than with where the
        // empty slice went. Measured that way: `cargo check -p scratchy-target-spyre` rc 101, against
        // rc 0 on main.
        Program::Elementwise(ew) => elementwise(name, ew, &r, &[], sym_id_base, layout),
        Program::SiluMul => silumul(name, &r, sym_id_base, layout),
        Program::RmsNorm => rmsnorm(name, k, &r, sym_id_base, layout),
        Program::ScalarMul => scalarmul(name, k, &r, sym_id_base, layout),
        Program::Matmul => matmul_proven(k, &r, sym_id_base, layout, quantized),
        Program::LmLast => lmlast(name, k, &r, sym_id_base, layout),
        Program::Rope => rope(name, &r, sym_id_base, layout, attn_params),
        Program::Attn => attn(name, k, &r, sym_id_base, layout, attn_params),
        // ⭐ NO DOOR TO CROSS. A transpose's descriptor is parameterised by the two extents its own
        // program states and by nothing about the model, so the arm is the body — unlike `rope`/`attn`
        // above, whose head geometry has to become const generics on this side.
        Program::Transpose => lk::transpose(name, &r, sym_id_base, layout),
    }
}

/// The orphan-rule carrier for [`lk::AttnAt`] — see the module header.
struct AttnAt<'a>(lk::AttnAt<'a>);

impl scratchy_subtile::model_geometry::OnAttnGeometry for AttnAt<'_> {
    type Out = Result<Vec<EmittedOp>, Error>;
    fn on_geometry<const NQH: u32, const NKVH: u32, const HD: u32>(
        self,
        geom: scratchy_subtile::sdsc_abstract::AttnGeometry<NQH, NKVH, HD>,
    ) -> Self::Out {
        attn_at::<NQH, NKVH, HD>(self.0, geom)
    }
}

/// ⭐ THE DOOR. main's `lower_attn_node` read its cache identity off `node.inputs` and `ir.tensors`,
/// its geometry and multiplier off the node's `SubOp`, and `active_cap`/`rows_are_requests` off its
/// call site. The first group the PROGRAM states, so `attn_at` reads it there (`attn_operands`); the
/// rest are [`BundleAttnParams`], main's own remaining parameters, stated for this bundle by the
/// caller. `mq` is [`KtirNode::out_shape`]'s row count, which is what main's `TileOp` `mb` dim was.
fn attn(
    name: &str,
    k: &KtirNode,
    r: &[Region],
    sym_id_base: &mut i64,
    layout: Option<&BundleLayout>,
    attn_params: Option<BundleAttnParams>,
) -> Result<Vec<EmittedOp>, Error> {
    let p = attn_params.ok_or_else(|| Error {
        message: format!(
            "{name}: an attention program reached the lowering with no `BundleAttnParams`. Its head \
             geometry and multiplier are the model's (main reads them off `SubOp::AttnDecode`) and \
             its swept rung and row kind are this bundle's (main's own walk parameters) — no KTIR \
             states any of the four, so the caller must state them at the door."
        ),
    })?;
    // ⭐⭐ THE ONE PLACE THE MODEL'S HEAD GEOMETRY STOPS BEING VALUES for the attention path — the SAME
    // door `lower_one_node` crossed, on the SAME value it crossed it with (carried, not re-minted, so
    // the GQA division is still evaluated exactly once).
    scratchy_subtile::model_geometry::with_config_attn_geometry(
        p.geom,
        AttnAt(lk::AttnAt {
            name,
            k,
            r,
            rows_are_requests: p.rows_are_requests,
            sym_id_base,
            layout,
        }),
    )
    .ok_or_else(|| Error {
        message: format!(
            "{name}: AttnDecode geometry has no const-generic instantiation. The head counts and \
             the head dim parameterise the device layout (GQA grouping, slabs, head strides), so \
             they must be consts, not values. The instantiations are read from the model configs in \
             scope ({}); this geometry belongs to none of them.",
            scratchy_subtile::model_geometry::geometry_sources(),
        ),
    })?
}

/// The orphan-rule carrier for [`lk::RopeAt`] — see the module header.
struct RopeAt<'a>(lk::RopeAt<'a>);

impl scratchy_subtile::model_geometry::OnHeadDim for RopeAt<'_> {
    type Out = Result<Vec<EmittedOp>, Error>;
    fn on_head_dim<const HD: u32>(self) -> Self::Out {
        rope_at::<HD>(self.0)
    }
}

/// ⭐ THE DOOR. main's `lower_rope_node` read `mq`/`total` off a `TileOp` built from the node and its
/// operand names off `ds_name`. `total` is the node's declared output width and `mq` its row count —
/// both carried on [`KtirNode::out_shape`], because the program states only their product with
/// `heads` (see that field). The head dim is the `x` view's own column extent, and it becomes the
/// const generic through the SAME door main crossed.
fn rope(
    name: &str,
    r: &[Region],
    sym_id_base: &mut i64,
    layout: Option<&BundleLayout>,
    attn_params: Option<BundleAttnParams>,
) -> Result<Vec<EmittedOp>, Error> {
    let (ins, out) = split_out(name, r, layout, 3)?;
    // `KtirFunc::rope` views `x` as `[rows·heads, hd]`, so the view's COLUMN extent is the head dim.
    let hd = ins[0].v_cols;
    // ⭐⭐⭐ ROWS AND WIDTH, BOTH READ OFF THE PROGRAM — AND THE READING IS THE TILE, NOT A VIEW.
    // `KtirFunc::rope` views `x` as `[rows·heads, hd]` and takes `self.tile(x_view, ri·heads, 0,
    // heads, half)` once per position, so the ACCESS TILE's row extent IS `heads` — the fact the two
    // view extents multiply together and neither states alone. `regions()` already records it as
    // `Region::r_len`. With `heads` known the view's own row count divides into the positions, and the
    // node's real width is `heads · hd`.
    //
    // ⛔ NOT THE COS VIEW. It looked like the answer — cos is one row per position — but `rope` binds
    // it through `load_1d(cos_t, rows·tbl_cols, ri·tbl_cols, half)`, i.e. ONE-DIMENSIONAL, so its view
    // is `(1, rows·tbl_cols)` and its row extent is 1 for every model. Reading it as the position
    // count made granite-3.1-8b's `[2, 4096]` rope output into `[1, 8192]`, which the arrangement
    // authority caught as a same-tensor layout conflict on t729. The half-width is `c_len` here, so
    // `hd == 2 · c_len` is checked below rather than assumed.
    let heads = ins[0].r_len;
    if heads == 0 || hd == 0 {
        return err(format!(
            "{name}: the `x` view states `[{}, {hd}]` and its access tile {heads} row(s) — a rope \
             needs a nonzero head dim and at least one head",
            ins[0].v_rows,
        ));
    }
    if ins[0].v_rows % heads != 0 {
        return err(format!(
            "{name}: the `x` view states {} row(s) over an access tile of {heads} head(s), which does \
             not divide — `KtirFunc::rope` views `x` as `rows·heads` by `hd`, so the head count must \
             tile its rows exactly",
            ins[0].v_rows,
        ));
    }
    if ins[0].c_len * 2 != hd {
        return err(format!(
            "{name}: the `x` access tile takes {} column(s) of a {hd}-wide view — a rope rotates \
             half-width slices, so the window must be exactly `hd / 2`",
            ins[0].c_len,
        ));
    }
    let mq = ins[0].v_rows / heads;
    let total = heads * hd;
    // ⛔ THE ROW KIND, AS A PARAMETER — main's `LowerRope::rows_are_requests`, which main also took as
    // a parameter and for the reason its own comment gives. It decides whether the head-major collapse
    // may span the query rows, which is a DEVICE law: `KtirFunc::rope` never receives the fact and
    // emits the same ops either way, so no program can state it. A rope in a bundle with no attention
    // node has no requests to have rows of, which is main's own `false` at that call site.
    let rows_are_requests = attn_params.is_some_and(|p| p.rows_are_requests);
    // ⭐⭐ THE ONE PLACE THE HEAD DIM STOPS BEING A VALUE, the same door `lower_one_node` crossed for
    // the SubtileIR path: the arms are every head dim the workspace's model configs declare, and a
    // head dim with no arm is a loud bake error answered by a `config.json`.
    if hd == 0 {
        return err(format!("{name}: the `x` view states a zero head dim"));
    }
    scratchy_subtile::model_geometry::with_config_head_dim(
        scratchy_subtile::model_geometry::HeadDim::new(hd),
        RopeAt(lk::RopeAt {
            name,
            x: ins[0].name(),
            cos: ins[1].name(),
            sin: ins[2].name(),
            out: out.name(),
            t: out.tid,
            mq,
            total,
            sym_id_base,
            layout,
            rows_are_requests,
        }),
    )
    .ok_or_else(|| Error {
        message: format!(
            "{name}: head_dim {hd} has no const-generic instantiation. The head dim parameterises \
             the device layout (slabs = head_dim/lanes, and the head-major collapse is valid only at \
             head_dim == lanes), so it must be a const, not a value. The instantiations are read \
             from the model configs in scope ({}); this head dim belongs to none of them.",
            scratchy_subtile::model_geometry::geometry_sources(),
        ),
    })?
}
