//! THE ORACLE TEST: our TTIR against what the existing Python toolchain emits.
//!
//! Needs the `ruff` feature: every case starts from Python SOURCE.
#![cfg(feature = "ruff")]
//!
//! The goldens are regenerated by
//! `tools/gen_ttir_goldens.py`, which writes TWO checkpoints per configuration:
//!
//!   * `<name>.ttir_raw.mlir` -- `ASTSource.make_ir(...)`, i.e. `code_generator.py`'s
//!     output. THIS is bridge one's oracle, because it is exactly what this crate ports.
//!   * `<name>.ttir.mlir` -- after `backend.make_ttir(...)`, which is a PASS PIPELINE
//!     (inliner, canonicalizer, ttir-combine, reorder-broadcast, cse, symbol-dce). That is
//!     bridge two's input, not ours; diffing against it would demand we also reproduce MLIR
//!     canonicalization.
//!
//! Comparison is STRUCTURAL and field by field -- see `triton_frontend::diff` for exactly
//! what is and is not compared. `planted_difference_*` below are the CONTROLS: without a
//! test that a deliberately-broken module is caught AND NAMED, a passing diff proves
//! nothing.

mod common;

use triton_frontend::codegen;
use triton_frontend::diff;
use triton_frontend::target::Target;
use triton_frontend::ttir::{self, Attr, Type};

/// Compile a fixture at `target` and compare it against its golden, printing the full
/// field-by-field report on failure.
///
/// # WHICH TARGET, AND WHY IT IS NOT ALWAYS SPYRE.
///
/// The goldens were produced by the real Triton, which HAS the `f16 / f16 -> f32` promotion
/// this crate deliberately turns off for Spyre (see `triton_frontend::target`). Five of the
/// seven configurations never reach a bare `/` on f16 -- `swiglu_mlp.py` uses `tl.fdiv`
/// precisely to dodge the promotion -- so they match under EITHER target, and
/// `every_matching_fixture_is_target_independent` asserts exactly that.
///
/// `attention_flash.py`'s epilogue is the exception: `acc = acc / l_i[:, None]` is a bare f16
/// divide, so the oracle widens it. Diffed with `upstream_gpu` it matches exactly, which is
/// what proves the PORT faithful; `tests/divergence.rs` then asserts that under `spyre` the
/// difference is exactly that divide and nothing else, which is what proves the DIVERGENCE
/// real and localized. Using one target for both jobs would have lost one of the two facts.
fn check_case_on(case: &common::Case, target: Target) {
    let name = &case.name;
    let kernel = &case.spec.kernel;
    let spec = &case.spec;
    // The golden NAME and the source FILE differ for the multi-configuration fixtures:
    // `swiglu_mlp_granite` is `swiglu_mlp.py` at Granite width.
    let src = common::fixture_src(&case.fixture);
    let golden = match common::golden(name) {
        Some(g) => g,
        None => panic!(
            "no golden for `{name}`: expected tests/goldens/{name}.ttir_raw.mlir. \
             Regenerate with tools/gen_ttir_goldens.py."
        ),
    };
    let ours = match codegen::compile(&src, spec, target) {
        Ok(m) => m,
        Err(e) => panic!("`{name}` ({kernel}) did not compile: {e}"),
    };
    let report = diff::compare_to_golden_text(&golden, &ours);
    if !report.ok() {
        eprintln!("---- OUR TTIR for {name} ----\n{}", ttir::print::print_module(&ours));
        panic!(
            "`{name}` does not match its golden structurally:\n{}",
            report.render()
        );
    }
    assert!(
        report.matched_ops > 0,
        "`{name}`: the diff reported no findings but also matched ZERO ops -- that is a \
         diff comparing nothing, not a pass"
    );
    eprintln!("{name}: {} op(s) matched structurally", report.matched_ops);
}

fn check_case(case: &common::Case) {
    check_case_on(case, Target::spyre());
}

/// [`check_case_on`] for a golden that is KNOWN STALE: the diff must yield exactly
/// `pinned_findings` findings, so the staleness is asserted rather than hidden. 0 findings
/// or a larger count both fail, forcing the entry back to [`check_case_on`] or a
/// re-recorded pin with a reason.
fn check_case_stale_on(case: &common::Case, target: Target, pinned_findings: usize) {
    let name = &case.name;
    let src = common::fixture_src(&case.fixture);
    let golden = common::golden(name).unwrap_or_else(|| {
        panic!("no golden for `{name}`: expected tests/goldens/{name}.ttir_raw.mlir")
    });
    let ours = codegen::compile(&src, &case.spec, target)
        .unwrap_or_else(|e| panic!("`{name}` did not compile: {e}"));
    let report = diff::compare_to_golden_text(&golden, &ours);
    let got = report.findings.len();
    assert!(
        report.matched_ops > 0,
        "`{name}`: the diff matched ZERO ops -- that is a diff comparing nothing"
    );
    assert_eq!(
        got, pinned_findings,
        "`{name}`: the stale-golden pin moved ({pinned_findings} recorded, {got} now): \
         regenerate the golden and use check_case_on, or re-record the pin AND file why.\n{}",
        report.render()
    );
}

/// The configurations that never reach a bare f16 divide, and so are target-independent.
fn target_independent_cases() -> Vec<common::Case> {
    vec![
        common::vector_add(),
        common::mul(),
        common::swiglu("swiglu_mlp", 128, 256, 128),
        common::swiglu("swiglu_mlp_granite", 4096, 12800, 4096),
        common::swiglu("swiglu_mlp_tiledk", 128, 256, 64),
        common::embedding("embedding", 512, 128),
        common::embedding("embedding_granite", 49159, 4096),
        common::rmsnorm("rmsnorm", 128),
        common::rmsnorm("rmsnorm_granite", 4096),
        common::rope("rope", 4),
        common::rope("rope_granite_q", 32),
        common::rope("rope_granite_kv", 8),
        common::decoder_layer(),
        common::decoder_two_layers(),
    ]
}

#[test]
fn vector_add_matches_golden() {
    check_case(&common::vector_add());
}

#[test]
fn mul_matches_golden() {
    check_case(&common::mul());
}

#[test]
fn swiglu_mlp_matches_golden() {
    check_case(&common::swiglu("swiglu_mlp", 128, 256, 128));
}

/// Granite width: same kernel, `D_MODEL` 4096 and `D_FF` 12800. Shapes are constexpr, so
/// this is a different program, not the same one at a different size.
#[test]
fn swiglu_mlp_granite_matches_golden() {
    check_case(&common::swiglu("swiglu_mlp_granite", 4096, 12800, 4096));
}

/// `BLOCK_K < D_MODEL`, which makes the inner `scf.for` a genuinely NESTED loop rather than
/// one the canonicalizer deletes -- the configuration that exercises carry discovery inside
/// an enclosing loop.
#[test]
fn swiglu_mlp_tiledk_matches_golden() {
    check_case(&common::swiglu("swiglu_mlp_tiledk", 128, 256, 64));
}

/// Granite's input embedding: the ONLY fixture with an indirect address
/// (`tt.descriptor_gather`), and the only one with a non-float descriptor -- so it is also
/// the only golden that exercises the `si32` block-element spelling.
#[test]
fn embedding_matches_golden() {
    check_case(&common::embedding("embedding", 512, 128));
}

/// The same kernel at Granite's own vocabulary and hidden size (49159 x 4096). Shapes are
/// constexpr, so this is a different program rather than the same one at a different size.
#[test]
fn embedding_granite_matches_golden() {
    check_case(&common::embedding("embedding_granite", 49159, 4096));
}

/// Granite's RMSNorm: a `tl.sum` reduction (which brings in two generated `standard.*`
/// functions and a `tt.reduce` region), the `math.rsqrt` inside its f32 island, and a
/// broadcast of a 1D weight along the rows -- `tt.expand_dims` on BOTH axes, which no earlier
/// fixture does (attention expands axis 1 only).
#[test]
fn rmsnorm_matches_golden() {
    check_case(&common::rmsnorm("rmsnorm", 128));
}

/// The same kernel at Granite's hidden size, 4096 -- 64 sticks of reduction rather than 2.
#[test]
fn rmsnorm_granite_matches_golden() {
    check_case(&common::rmsnorm("rmsnorm_granite", 4096));
}

/// Granite's RoPE. Two things no earlier fixture has: FOUR descriptor loads of which two read
/// the SAME descriptor at different column offsets (the split-half rotation, which at head_dim
/// 128 in f16 is a whole-stick swap), and TWO stores.
#[test]
fn rope_matches_golden() {
    check_case(&common::rope("rope", 4));
}

/// Granite's 32 query heads.
#[test]
fn rope_granite_q_matches_golden() {
    check_case(&common::rope("rope_granite_q", 32));
}

/// Granite's 8 kv heads -- the same source, the other launch of the pair.
#[test]
fn rope_granite_kv_matches_golden() {
    check_case(&common::rope("rope_granite_kv", 8));
}

/// A WHOLE Granite decoder block in one kernel: norm, q/k/v, RoPE, one-pass SDPA with an
/// additive causal mask, the output projection, the residual, the second norm, the SwiGLU MLP
/// and the second residual.
#[test]
fn decoder_layer_matches_golden() {
    check_case(&common::decoder_layer());
}

/// THE FUSION EXPERIMENT: the same block function called TWICE, with the hidden state between
/// the layers never touching memory. Its 57-argument flattened call (12 descriptors plus a
/// tensor) is the widest function boundary in the tree.
#[test]
fn decoder_two_layers_matches_golden() {
    check_case(&common::decoder_two_layers());
}

/// Flash attention, non-causal (`STAGE = 1`): the kernel plus a generated `_attn_fwd_inner`
/// and four generated `standard.*` helpers, two of which carry a `tt.reduce` region.
///
/// Diffed against the UPSTREAM target -- see `check_case_on` for why.
///
/// STALE GOLDEN, pinned: 11 findings at triton-spyre tip `5c51a1d7a` (re-hosted verbatim) --
/// the descriptor mangling and constant placement the diff names. If this moves to 0, the
/// golden was regenerated: switch back to `check_case_on`. If it grows, the front end
/// drifted: re-record AND file why. See `tests/fixture_status.rs`'s
/// `Expect::MatchesStaleGolden` for the same pin at the status-table level.
#[test]
fn attention_flash_noncausal_matches_golden() {
    check_case_stale_on(
        &common::attention("attention_flash_noncausal", 1),
        Target::upstream_gpu(),
        11,
    );
}

/// Flash attention, causal (`STAGE = 3`): the inner helper is instantiated TWICE, at
/// `4 - STAGE = 3` and at `2`, so the module carries two differently-mangled copies of it.
#[test]
fn attention_flash_causal_matches_golden() {
    check_case_on(
        &common::attention("attention_flash_causal", 3),
        Target::upstream_gpu(),
    );
}

/// The five fixtures that avoid a bare f16 divide must match under BOTH targets.
///
/// This is the control that keeps the divergence honest in the other direction: if
/// `div_promotes_narrow_floats` ever started affecting anything other than a narrow-float
/// divide, these would stop agreeing.
#[test]
fn every_matching_fixture_is_target_independent() {
    for case in target_independent_cases() {
        let src = common::fixture_src(&case.fixture);
        let golden = common::golden(&case.name).expect("golden");
        for target in [Target::spyre(), Target::upstream_gpu()] {
            let m = codegen::compile(&src, &case.spec, target)
                .unwrap_or_else(|e| panic!("`{}` did not compile: {e}", case.name));
            let r = diff::compare_to_golden_text(&golden, &m);
            assert!(
                r.ok(),
                "`{}` should match its golden under EVERY target, but with {target:?} it has \
                 {} finding(s):\n{}",
                case.name,
                r.findings.len(),
                r.render()
            );
        }
    }
}

// ===----------------------------------------------------------------------===//
//   THE CONTROLS: a planted difference of each kind must be caught, BY NAME.
// ===----------------------------------------------------------------------===//

/// Compile vector_add and also parse its golden, so a mutation can be planted in one side.
fn both_sides() -> (ttir::Module, ttir::Module) {
    let src = common::fixture_src("vector_add");
    let golden = common::golden("vector_add").expect("vector_add golden");
    let expected = ttir::parse::parse_module(&golden)
        .unwrap_or_else(|e| panic!("golden did not parse: {e}"));
    let ours = codegen::compile(&src, &common::vector_add().spec, Target::spyre())
        .expect("vector_add compiles");
    (expected, ours)
}

fn findings_mentioning(report: &diff::Report, needle: &str) -> Vec<String> {
    report
        .findings
        .iter()
        .filter(|f| f.contains(needle))
        .cloned()
        .collect()
}

/// The baseline the controls depend on: unmutated, the two sides agree. If this fails the
/// controls below prove nothing either.
#[test]
fn control_baseline_is_clean() {
    let (expected, ours) = both_sides();
    let r = diff::compare(&expected, &ours);
    assert!(
        r.ok(),
        "the control baseline is not clean, so no planted-difference control below is \
         meaningful:\n{}",
        r.render()
    );
    assert!(r.matched_ops > 0, "baseline matched zero ops");
}

fn first_func_ops(m: &mut ttir::Module) -> &mut Vec<ttir::Op> {
    &mut m.funcs[0].body.blocks[0].ops
}

#[test]
fn control_planted_op_name_is_caught() {
    let (expected, mut ours) = both_sides();
    // `arith.addf` -> `arith.mulf`: the vector_add/mul distinction, i.e. the difference
    // that matters most and would be silent if the diff ignored op names.
    let mut hit = false;
    for op in first_func_ops(&mut ours) {
        if op.name == "arith.addf" {
            op.name = "arith.mulf".to_string();
            hit = true;
        }
    }
    assert!(hit, "control could not find an arith.addf to mutate");
    let r = diff::compare(&expected, &ours);
    let found = findings_mentioning(&r, ".name:");
    assert!(
        !found.is_empty() && found[0].contains("arith.addf") && found[0].contains("arith.mulf"),
        "a planted op-name change was not caught by name. Findings: {:?}",
        r.findings
    );
}

#[test]
fn control_planted_result_type_is_caught() {
    let (expected, mut ours) = both_sides();
    // Retype one `tt.descriptor_load` result from tensor<64xf16> to tensor<64xf32>.
    let target = first_func_ops(&mut ours)
        .iter()
        .find(|o| o.name == "tt.descriptor_load")
        .and_then(|o| o.results.first().copied())
        .expect("control could not find a tt.descriptor_load result");
    ours.values[target.0 as usize].ty = Type::tensor(&[64], Type::f32());
    let r = diff::compare(&expected, &ours);
    let found = findings_mentioning(&r, ".result_types:");
    assert!(
        !found.is_empty() && found[0].contains("tensor<64xf32>"),
        "a planted result-TYPE change was not caught by name. Findings: {:?}",
        r.findings
    );
}

#[test]
fn control_planted_shape_is_caught() {
    let (expected, mut ours) = both_sides();
    // Same element type, different SHAPE -- the failure a type-only comparison would miss.
    let target = first_func_ops(&mut ours)
        .iter()
        .find(|o| o.name == "tt.descriptor_load")
        .and_then(|o| o.results.first().copied())
        .expect("control could not find a tt.descriptor_load result");
    ours.values[target.0 as usize].ty = Type::tensor(&[128], Type::f16());
    let r = diff::compare(&expected, &ours);
    let found = findings_mentioning(&r, ".result_types:");
    assert!(
        !found.is_empty() && found[0].contains("tensor<128xf16>"),
        "a planted SHAPE change was not caught by name. Findings: {:?}",
        r.findings
    );
}

#[test]
fn control_planted_attribute_is_caught() {
    let (expected, mut ours) = both_sides();
    // Change a constant's value: 64 -> 63. Structurally identical otherwise.
    let mut hit = false;
    for op in first_func_ops(&mut ours) {
        if op.name == "arith.constant" {
            if let Some(Attr::Int(v, t)) = op.attrs.get("value").cloned() {
                if v == 64 {
                    op.attrs.insert("value".to_string(), Attr::Int(63, t));
                    hit = true;
                    break;
                }
            }
        }
    }
    assert!(hit, "control could not find an `arith.constant 64` to mutate");
    let r = diff::compare(&expected, &ours);
    let found = findings_mentioning(&r, ".attr[value]:");
    assert!(
        !found.is_empty() && found[0].contains("63"),
        "a planted ATTRIBUTE change was not caught by name. Findings: {:?}",
        r.findings
    );
}

#[test]
fn control_planted_predicate_is_caught() {
    let (expected, mut ours) = both_sides();
    // `arith.cmpi sle` -> `sgt`: the overflow check's bound direction.
    let mut hit = false;
    for op in first_func_ops(&mut ours) {
        if op.name == "arith.cmpi" {
            if let Some(Attr::Pred("sle")) = op.attrs.get("predicate") {
                op.attrs
                    .insert("predicate".to_string(), Attr::Pred("sgt"));
                hit = true;
                break;
            }
        }
    }
    assert!(hit, "control could not find an `arith.cmpi sle` to mutate");
    let r = diff::compare(&expected, &ours);
    let found = findings_mentioning(&r, ".attr[predicate]:");
    assert!(
        !found.is_empty() && found[0].contains("sgt"),
        "a planted PREDICATE change was not caught by name. Findings: {:?}",
        r.findings
    );
}

#[test]
fn control_planted_operand_swap_is_caught() {
    let (expected, mut ours) = both_sides();
    // Swap the two operands of the real `arith.muli` (the i32 one, whose operands differ):
    // same ops, same types, same counts, DIFFERENT dataflow.
    let mut hit = false;
    for op in first_func_ops(&mut ours) {
        if op.name == "arith.muli" && op.operands.len() == 2 && op.operands[0] != op.operands[1] {
            op.operands.swap(0, 1);
            hit = true;
            break;
        }
    }
    assert!(hit, "control could not find an `arith.muli` to mutate");
    let r = diff::compare(&expected, &ours);
    let found = findings_mentioning(&r, ".operands:");
    assert!(
        !found.is_empty(),
        "a planted OPERAND swap was not caught -- the diff is not comparing dataflow. \
         Findings: {:?}",
        r.findings
    );
}

#[test]
fn control_planted_missing_op_is_caught() {
    let (expected, mut ours) = both_sides();
    let before = first_func_ops(&mut ours).len();
    first_func_ops(&mut ours).retain(|o| o.name != "arith.andi");
    let after = first_func_ops(&mut ours).len();
    assert!(after < before, "control removed nothing");
    let r = diff::compare(&expected, &ours);
    let found = findings_mentioning(&r, ".op_count:");
    assert!(
        !found.is_empty(),
        "a planted op COUNT change was not caught. Findings: {:?}",
        r.findings
    );
    assert_eq!(
        r.actual_hist.get("arith.andi").copied().unwrap_or(0),
        0,
        "the histogram should show the removed op as absent"
    );
    assert!(
        r.expected_hist.get("arith.andi").copied().unwrap_or(0) > 0,
        "the histogram should show the golden still has it"
    );
}

#[test]
fn control_planted_loc_name_is_caught() {
    let (expected, mut ours) = both_sides();
    // The `loc` NAME is the Python variable, so it is AST-derived content, not cosmetics.
    let target = first_func_ops(&mut ours)
        .iter()
        .find(|o| o.name == "tt.get_program_id")
        .and_then(|o| o.results.first().copied())
        .expect("control could not find tt.get_program_id");
    let l = ours.values[target.0 as usize].loc.clone();
    ours.values[target.0 as usize].loc = l.named("NOT_pid");
    let r = diff::compare(&expected, &ours);
    let found = findings_mentioning(&r, ".result_loc_names:");
    assert!(
        !found.is_empty() && found[0].contains("NOT_pid"),
        "a planted loc-NAME change was not caught by name. Findings: {:?}",
        r.findings
    );
}

#[test]
fn control_planted_function_name_is_caught() {
    let (expected, mut ours) = both_sides();
    ours.funcs[0].name = "not_the_kernel".to_string();
    let r = diff::compare(&expected, &ours);
    assert!(
        findings_mentioning(&r, "MISSING in ours")
            .iter()
            .any(|f| f.contains("vector_add_kernel"))
            && findings_mentioning(&r, "EXTRA in ours")
                .iter()
                .any(|f| f.contains("not_the_kernel")),
        "a planted FUNCTION-name change was not caught by name. Findings: {:?}",
        r.findings
    );
}

/// The control that guards the control: a golden that does not parse must FAIL, never pass
/// silently. This is the specific way an oracle test can look green while comparing
/// nothing.
#[test]
fn control_unparsable_golden_fails_rather_than_passes() {
    let (_, ours) = both_sides();
    let r = diff::compare_to_golden_text("this is not MLIR at all", &ours);
    assert!(!r.ok(), "an unparsable golden must not compare clean");
    assert!(
        r.findings[0].contains("golden did not parse"),
        "the finding should say the golden did not parse, got {:?}",
        r.findings
    );
}
