#!/bin/bash
# TYPES campaign driver: the `dsc/` TYPE definitions and their FIELDS — the units every prior
# per-function campaign excluded as "a struct field, not a function to port".
#   port wave(s) -> promote session branch -> review pass -> promote -> deeptools gate
#
# ⭐ THE BURNDOWN THIS DRIVER PRINTS IS FIELD COVERAGE, NOT ANCHORS. See `count` below: anchors are a
# progress signal, `todo!` under schedule/stages/ is the stub debt, and FIELDS CARRIED BY THE RUST
# TYPE is the number whose absence let 101 stubs accumulate. All three, every stage.
# Every stage's own log is under logs/; this script's own trace is logs/driver.trace.
#
# ⛔ EVERY GUARD BELOW IS A SCAR FROM THE BRIDGE-1, BRIDGE-2 AND DDC CAMPAIGNS. Do not simplify one
# away, and do not edit this file WHILE IT IS RUNNING — bash reads a script by byte offset, so an
# in-place edit reorders the rest of the run. Change it with `mv` onto a fresh copy.
# ⛔ NEVER COMMIT TO A BRANCH THIS DRIVER IS WRITING. That stranded 90 units on one campaign and 67
# on another.
ROOT=/Users/nickm/git/scratchy/.claude/worktrees/bridge1-pr
BRANCH=$(git -C $ROOT rev-parse --abbrev-ref HEAD)
CAMP=$ROOT/crustify/campaigns/types
LOGDIR=$CAMP/logs
TRACE=$LOGDIR/driver.trace
mkdir -p $LOGDIR
say() { echo "[$(date +%H:%M:%S)] $*" >> $TRACE; }

# ⭐ (0) ONE SHARED CARGO TARGET. Parallel agents each get their own worktree; without this each
# grows its own 6 GB target/ and the host wedges. It also means A GATE CAN GO GREEN ON SOMEONE
# ELSE'S BUILD — read the log, never just the exit code.
export CARGO_TARGET_DIR=$ROOT/target

# ⛔⛔ (1) SINGLE-INSTANCE LOCK. THREE SEPARATE INCIDENTS ON BRIDGE 2 CAME FROM TWO DRIVERS AT ONCE:
# duplicate drivers share every log path under $LOGDIR, each overwrites the other's stage log, and
# `promote` reads the session branch name OUT of that log. The older driver promoted a branch the
# younger one owned, HEAD moved sideways, and nine batches of finished work were stranded.
# ⛔⛔ NEVER `rm -f` THIS FILE TO CLEAR A "STALE" LOCK. The `kill -0` below already handles a
# genuinely stale lock. If a LIVE driver holds it, kill the driver and let its EXIT trap release it —
# and kill its `crustify` CHILD too, because killing the bash script alone reparents the child to
# init, which keeps spawning agents:
#     pkill -f 'crustify .*worktrees/bridge1-pr'
# ⚠ This path is deliberately NOT crustify/campaigns/.driver.lock — that file is TRACKED IN GIT and
# this worktree's checkout of it holds a pid owned by another worktree's driver.
# ⛔⛔ (1a) A DIRTY TREE MEANS ANOTHER AGENT IS WRITING THIS BRANCH — REFUSE.
# `promote` runs `git merge --ff-only`, `git rebase` and `git checkout` against $ROOT. With another
# agent's UNCOMMITTED work in the tree those either fail or discard it, and this worktree is shared:
# when this campaign was staged, two fenced agents held live edits to schedule/l3/dl_ops.rs,
# schedule/stages/tree.rs and schedule/stages/state.rs, one of them touched one second earlier.
# ⛔ THE FIX IS NEVER `git stash` — the stash stack is shared with every other worktree and popping
# it can take another session's work. Wait for the tree to be clean, or commit the other agent's work
# WITH that agent, then start this driver.
dirty=$(git -C $ROOT status --porcelain --untracked-files=no)
if [ -n "$dirty" ]; then
  echo "REFUSING TO START: $ROOT has uncommitted changes — another agent is writing this branch:" >&2
  echo "$dirty" >&2
  say "REFUSED: dirty tree, another agent is writing $BRANCH"
  printf '%s\n' "$dirty" >> $TRACE
  exit 8
fi

LOCK=$CAMP/.driver.lock
if [ -e "$LOCK" ] && kill -0 "$(cat $LOCK 2>/dev/null)" 2>/dev/null; then
  echo "driver already running as pid $(cat $LOCK) — refusing to start a second" >&2
  say "REFUSED: driver already running as pid $(cat $LOCK)"
  exit 9
fi
echo $$ > "$LOCK"
trap 'rm -f "$LOCK"' EXIT INT TERM
say "LOCK acquired by pid $$ on $BRANCH"

# ⛔⛔ (2) THE .done MARKERS LIVE OUTSIDE THE CAMPAIGN DIR. crustify's `link_shared` symlinks the
# campaign directory into each agent worktree, which turned every .done-<tag> into a SYMLINK POINTING
# AT ITSELF: `[ -f ]` then failed, 7 batches died in 7 seconds.
# ⛔⛔ AND THE MARKER DIRECTORY IS PER-CAMPAIGN, BECAUSE THE STAGE TAGS ARE NOT UNIQUE. Every campaign
# names its stages sc1-port, sc2-port, sc1-review… so a shared $ROOT/.campaign-done makes two
# campaigns collide on one filename. MEASURED, not theoretical: on this campaign's first launch
# (2026-09-16 19:32) the types driver read capacity's `.done-sc1-port`, called it stale because ITS
# remainder had 16 units, and `rm -f`'d ANOTHER CAMPAIGN'S COMPLETION RECORD — then did the same to
# `.done-sc2-port`. Capacity had finished, so nothing was lost; had it been mid-run, its next launch
# would have silently re-ported two finished waves.
STATE=$ROOT/.campaign-done/types
mkdir -p $STATE

# ⭐ (3) ANCHOR CENSUS — A PROGRESS SIGNAL, NEVER THE GATE. "1,076 units ported" once meant 238
# stubs. OUTSTANDING WORK IS JUDGED FROM UNITS.tsv AND FROM `todo!` COUNTS, never from anchors.
#
# ⛔ SCOPED TO THIS CAMPAIGN'S OWN HOME FILES AND ITS OWN 18 NAMES. The first version grepped the
# whole crate for `e0NN_` and reported "filled=72 of 18" — nonsense, because e002-e019 are also
# bridge-1 and ddc entry numbers on entirely different functions. A counter that can never read
# 17-of-18 can never trip the ANCHOR LOSS alarm below, which is the safeguard that catches a stage
# silently dropping units. The home list is exactly UNITS.tsv's rust_home column.
# ⛔⛔ DERIVED FROM UNITS.tsv'S rust_home COLUMN, NEVER HAND-LISTED. A home missing from this list is
# the one bad-anchor-filter case that LOSES WORK rather than misreporting it: `count` never sees that
# unit's anchor, `remainders` therefore never drops it, and it is re-ported on every restart forever.
# The first hand-written version of this line named l3/dims.rs (which does not exist) and omitted
# ddc/transformation_util.rs, ddc/v1.rs and ddc/metadata.rs — three of the five real homes.
UNITS_TSV=$ROOT/crustify-types/UNITS.tsv
HOMES=$(awk -F'\t' 'NR>1 {sub(/:.*/,"",$6); sub(/ \(NEW\)/,"",$6); if ($6!="") print "'"$ROOT"'/crates/compiler/deeptools/src/" $6}' $UNITS_TSV | sort -u)
NAMES=$(awk -F'\t' 'NR>1 && $2!="-" {print $1}' $UNITS_TSV | sort -u)
NUNITS=$(printf '%s\n' "$NAMES" | grep -c .)
LAST_FILLED=-1
count() {
  filled=$(grep -hoE '/// Replaces: e[0-9]{3}_[A-Za-z0-9_]+' $HOMES 2>/dev/null \
             | sed 's|/// Replaces: ||' | sort -u | grep -Fxf <(printf '%s\n' "$NAMES") | wc -l | tr -d ' ')
  # ⛔ NON-COMMENT LINES ONLY, the same rule `dfir_never_runtime_refuses.rs` counts by. The first
  # version read `todo! in capacity.rs=1` on an EMPTY module, because the module doc says the words
  # "no `todo!` bodies". A censor that counts its own prose reports work that is not there.
  #
  # ⭐ THE STUB DEBT IS THE WHOLE CARRIER LAYER, because this campaign's acceptance is that the layer
  # is DELETED. Counting only one file would report a green campaign with 130 stubs still standing.
  todos=$(grep -rhE 'todo!' $ROOT/crates/compiler/deeptools/src/schedule/stages* 2>/dev/null \
            | grep -vE '^\s*(//|/\*|\*)' | wc -l | tr -d ' ')
  # ⭐⭐ THE BURNDOWN: how many of DesignSpaceConfig's 49 C++-declared fields the RUST TYPE carries.
  # Measured 9 on 2026-09-16, with 19 more carried ELSEWHERE in the crate and 21 nowhere — and
  # "elsewhere" is precisely the defect (`scheduleTree_` in a second home, `name_`/`computeOp_` handed
  # in as construction arguments). So this counts fields ON THE STRUCT ITSELF, never crate-wide.
  # ⚠ The denominator is C++'s, re-derived each run from the VENDORED header so it cannot drift from
  # the authority; the vendored copy is byte-identical to dsc/designSpaceConfig.h (checked at staging).
  # ⛔ COUNT C++ FIELDS **CITED** IN THE RUST BODY, NOT RUST `pub` LINES. The first version counted
  # `^\s+pub [a-z_]+:` and printed "12 of 49" where the answer is 9: a Rust field is not necessarily
  # one of the C++ 49 (`ddc: DdcFacts` is a grouping of four), so that ratio silently flatters itself
  # and would keep doing so as groupings were added. The citation IS the evidence the field was ported.
  # ⛔⛔ DECLARATIONS ONLY. The first version matched any `name_` followed by `;`, `=` or `[` inside the
  # class span, which swept up MEMBER ACCESSES in the class's own method bodies and inflated the
  # denominator from 36 to 49: `paramNameToVal["ni"] = &N_.i_;` (designSpaceConfig.h:618) contributed
  # i_, and `return primaryDsInfo_.at(dsType).stickDimOrder_;` (:242) contributed stickDimOrder_ —
  # thirteen names in total (c_ i_ ij_ j_ mb_ out_ r_ rc_ stickDimOrder_ x_ y_ zi_ zj_) that belong to
  # NESTED types, not to DesignSpaceConfig. A burndown whose denominator counts other types' fields
  # reports a gap that does not exist; this one was quoted as "9 of 49" for a whole session.
  cppf_list=$(awk '/^class DesignSpaceConfig/,/^};/' $ROOT/crustify-types/cpp/designSpaceConfig.h 2>/dev/null \
           | grep -vE 'return|\(|\.|->|&|\["|^\s*//' \
           | grep -oE '\b[a-zA-Z][a-zA-Z0-9]*_\b\s*(\[[^]]*\])?\s*(=[^;]*)?;' \
           | grep -oE '^[a-zA-Z][a-zA-Z0-9]*_' | sort -u)
  cppf=$(printf '%s\n' "$cppf_list" | grep -c .)
  rbody=$(awk '/pub struct DesignSpaceConfig/,/^}/' $ROOT/crates/compiler/deeptools/src/schedule/l3/dsc.rs 2>/dev/null)
  rustf=0
  for f in $cppf_list; do
    printf '%s' "$rbody" | grep -q "\`$f\`" && rustf=$((rustf+1))
  done
  say "ANCHORS: filled=$filled of $NUNITS   todo! under stages/=${todos:-0}   DesignSpaceConfig fields: ${rustf:-0} of ${cppf:-0}"
  # ⛔⛔ ANCHOR LOSS. A stage that ends with FEWER anchors than it started with has dropped landed
  # work — a bad rebase, a promote that took the wrong branch, an agent that rewrote a file whole.
  # Stop and let a human look; the work is still on the session branch.
  if [ "$LAST_FILLED" -ge 0 ] && [ "$filled" -lt "$LAST_FILLED" ]; then
    say "⛔ ANCHOR LOSS: $LAST_FILLED -> $filled — landed units disappeared. STOPPING."
    exit 6
  fi
  LAST_FILLED=$filled
}

# ⭐ (4) REMAINDER SCHEDULES, AND THE REMAINDER OVERRULES THE MARKER. Rebuild each
# port-remainder.json from the anchors actually filled on the branch: the schedules are static and
# crustify has no idea which units are done, so without this a restart re-ports what already landed.
# ⛔⛔ SCOPED THE SAME WAY `count` IS, AND FOR A SHARPER REASON. The first version grepped the whole
# crate and handed the regenerator 72 anchors as "filled" — bridge-1 and ddc entry numbers on
# entirely different functions. It happened not to collide, but a collision DROPS A UNIT FROM THE
# REMAINDER THAT WAS NEVER PORTED, and nothing downstream would ever ask for it again. This is the
# one place a bad anchor filter loses work rather than just misreporting it.
remainders() {
  grep -hoE '/// Replaces: e[0-9]{3}_[A-Za-z0-9_]+' $HOMES 2>/dev/null \
    | sed 's|/// Replaces: ||' | sort -u \
    | grep -Fxf <(printf '%s\n' "$NAMES") > /tmp/filled-types.txt
  python3 $CAMP/regen-remainders.py >> $TRACE 2>&1
}

# ⭐ (5) PROMOTE BY FF-THEN-REBASE, never ff-or-die. A sideways HEAD — another promote, a hand
# commit — must not strand a stage's finished work on a session branch. On bridge 2 that stranded 48
# finished functions until they were rebased by hand.
promote() {
  br=$(grep -ohE 'crustify/session/[a-z]+-[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}_[0-9a-f]{4}' "$1" | tail -1)
  if [ -z "$br" ]; then say "PROMOTE: no session branch found in $1"; return 0; fi
  if git -C $ROOT merge --ff-only "$br" >> $TRACE 2>&1; then
    say "PROMOTE ok (ff): $br -> $(git -C $ROOT rev-parse --short HEAD)"
    remainders; return 0
  fi
  say "PROMOTE: not a fast-forward, rebasing $br onto $(git -C $ROOT rev-parse --short HEAD)"
  if git -C $ROOT rebase HEAD "$br" >> $TRACE 2>&1; then
    git -C $ROOT checkout - >> $TRACE 2>&1
    if git -C $ROOT merge --ff-only "$br" >> $TRACE 2>&1; then
      say "PROMOTE ok (rebased): $br -> $(git -C $ROOT rev-parse --short HEAD)"
      remainders; return 0
    fi
  fi
  git -C $ROOT rebase --abort >> $TRACE 2>&1
  git -C $ROOT checkout $BRANCH >> $TRACE 2>&1
  say "PROMOTE FAILED (rebase conflicted): $br — work is SAFE on that branch — STOPPING"
  exit 3
}

# ⭐ (6) DISK. Each agent worktree grows against the shared target/. Abort rather than wedge the host.
disk() {
  free=$(df -g $ROOT | awk 'NR==2{print $4}')
  say "DISK: ${free}G free"
  if [ "$free" -lt 12 ]; then say "DISK BELOW 12G — STOPPING"; exit 4; fi
}

# ⭐ (6) Prune promoted agent worktrees between stages, or the accumulated target/ dirs fill the disk.
prune() {
  git -C $ROOT worktree list --porcelain | grep -oE "$ROOT/crustify/.worktrees/[^ ]+" | while read -r w; do
    git -C $ROOT worktree remove --force "$w" >> $TRACE 2>&1
  done
  git -C $ROOT worktree prune >> $TRACE 2>&1
  say "PRUNED agent worktrees; $(df -g $ROOT | awk 'NR==2{print $4}')G free"
}

stage() { # $1 schedule json (relative to $CAMP)  $2 objective  $3 tag
  # ⭐ (7) SKIP A FINISHED STAGE — BUT THE REMAINDER OVERRULES THE MARKER. A .done marker beside a
  # NON-empty remainder means the marker is stale (a promote landed after it), so it is deleted and
  # the stage re-runs. Trusting the marker alone once had 9 agents re-reviewing 142 done functions.
  n=$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['summary']['unit_count'])" "$CAMP/$1" 2>/dev/null || echo 1)
  # ⛔⛔ THE REMAINDER-OVERRULES-MARKER RULE IS FOR **PORT** STAGES ONLY. A port stage's remainder is
  # regenerated from the anchors after every promote, so a non-empty remainder beside a .done marker
  # really does mean the marker is stale. A REVIEW stage reads review.json, which is STATIC and never
  # empties — so a finished review looks "stale" forever and is re-run on every single launch.
  # MEASURED 2026-09-17: sc1-review had completed at 06:57 and promoted EIGHT findings; a later launch
  # read `.done-sc1-review present but remainder has 16 units — MARKER IS STALE` and started the whole
  # 3h36m wave again. For a review, the marker is the only completion record there is: TRUST IT.
  # ⭐ To deliberately re-review (e.g. a unit was re-ported since), delete that one marker:
  #     rm .campaign-done/types/.done-<stage>-review
  if [ -f "$STATE/.done-$3" ] && [ "$2" = "review" ]; then
    say "STAGE $3 SKIPPED (.done-$3 present; a review schedule is static, so the marker is the record)"
    return 0
  fi
  if [ -f "$STATE/.done-$3" ]; then
    if [ "$n" = "0" ]; then
      say "STAGE $3 SKIPPED (.done-$3 present, remainder empty)"; return 0
    fi
    say "STAGE $3: .done-$3 present but remainder has $n units — MARKER IS STALE, re-running"
    rm -f "$STATE/.done-$3"
  fi
  if [ "$n" = "0" ]; then say "STAGE $3 SKIPPED (0 units left in $1)"; touch "$STATE/.done-$3"; return 0; fi
  disk
  # ⭐ (8) SMALL BATCHES, AND RETRY ONLY TRANSIENT API FAILURES — WITH AUTH CHECKED FIRST. crustify
  # promotes nothing until an agent completes, so at 50-unit batches an API drop at hour 4½ discarded
  # three agents' work. ⛔ AUTH FAILS FAST **BEFORE** THE TRANSIENT CHECK: retrying a 401 three times
  # at 120s burns 6 minutes and produces nothing, and the auth string can co-occur with a transient
  # one in the same log.
  for attempt in 1 2 3; do
    say "STAGE $3 start ($2, $1, $n units) attempt $attempt"
    crustify --parallel-max 3 $ROOT . translate "$CAMP/$1" --objective "$2" > $LOGDIR/driver-$3.log 2>&1
    rc=$?
    say "STAGE $3 attempt $attempt exit=$rc"
    [ $rc -eq 0 ] && break
    if grep -q "401 Authentication Error\|Invalid proxy server token\|Failed to authenticate\|Invalid API key" \
         $LOGDIR/driver-$3.log; then
      say "STAGE $3 AUTH FAILURE — not retrying, fix credentials and restart"; exit 7
    fi
    if ! grep -q "ENOTFOUND\|Can't reach the API server\|exited 1 for TranslateAgent" $LOGDIR/driver-$3.log; then
      say "STAGE $3 failed for a reason that is NOT the API — not retrying"; break
    fi
    say "STAGE $3 retrying in 120s (transient API failure)"; sleep 120
  done
  say "STAGE $3 exit=$rc"
  grep -E '^\[crustify\] [0-9]+ failure' $LOGDIR/driver-$3.log >> $TRACE 2>/dev/null
  promote $LOGDIR/driver-$3.log
  count
  prune
  # ⛔ ONLY A STAGE THAT EXITED 0 IS DONE. The first version touched the marker unconditionally, so
  # the three stages that died on a malformed schedule were all recorded as complete. The remainder
  # check above overrules a stale marker, so this never lost work — but a marker that lies about a
  # failure is a marker nobody can read, and it hid three failures behind "SKIPPED" on the next run.
  if [ "$rc" -eq 0 ]; then
    touch "$STATE/.done-$3"
  else
    say "STAGE $3 NOT marked done (exit=$rc) — it will re-run"
  fi
}

# ⛔ THE GATE IS deeptools ONLY. Never the workspace and never the acceptance build from here: 6 GB
# of target/ per agent worktree against <50 GB free.
gate() { # $1 tag
  ( cd $ROOT && cargo check -p deeptools > $LOGDIR/check-$1.log 2>&1 )
  say "CHECK $1 exit=$? :: $(grep -cE '^error' $LOGDIR/check-$1.log) errors"
  ( cd $ROOT && cargo test -p deeptools > $LOGDIR/test-$1.log 2>&1 )
  say "TEST $1 exit=$? :: $(grep -E '^test result' $LOGDIR/test-$1.log | tr '\n' ' ')"
  grep -E 'not yet implemented|panicked at|^error' $LOGDIR/check-$1.log $LOGDIR/test-$1.log | tail -5 >> $TRACE
}

say "=== TYPES CAMPAIGN START on $BRANCH at $(git -C $ROOT rev-parse --short HEAD) ==="
count
remainders

# ⭐⭐ EVERY PORT FIRST, THEN EVERY REVIEW — because a REVIEW IS NOT A DEPENDENCY.
#
# ⛔ THE OLD ORDER PUT REVIEWS ON THE CRITICAL PATH AND IT COST HOURS. Measured 2026-09-15:
# `sc1-port` took 34 min for its 2 remaining units (~17 min/unit, which is the real work), then
# `sc1-review` ran 25+ min on 7 units — and `sc2` + `sc3`, which are 11 units and 590 of the
# campaign's 734 lines, had NOT STARTED, queued behind it. Reviewing e002-e008 does not gate porting
# e009-e019: the dependency the wavefronts encode is between UNITS, and review adds none.
#
# ⛔ THE GATES STAY WHERE THEY ARE, one per sub-campaign after its port — `cargo check` + `cargo test`
# is what keeps a broken port from reaching the next wave, and that IS a dependency. Only the review
# barrier moves.
#
# ⭐ AND THE REVIEWS STILL RUN, ALL OF THEM. They are where the doc-versus-C++ defects surface: the
# 2026-09-15 review of an already-landed `pruneMaxSymbolicVolumes` found FOUR, including a seam
# calling a fused wrapper at a non-fused site and a `DT_CHECK` recovery that kept the LARGER bound
# where the reference aborts the compile. Dropping them to go faster would be trading the only pass
# that reads the authority for wall-clock.
stage sc1-node-hierarchy/port-remainder.json       port   sc1-port
gate sc1
stage sc2-designspaceconfig/port-remainder.json    port   sc2-port
gate sc2

stage sc1-node-hierarchy/review.json               review sc1-review
stage sc2-designspaceconfig/review.json            review sc2-review
gate reviews
say "CAMPAIGN DRIVER DONE — THE TYPES ARE THIS CAMPAIGN'S SCOPE, AND THE TYPES ARE NOT THE BRIDGE."
# ⛔⛔ WHAT THIS CAMPAIGN DELIBERATELY DOES NOT DO, SO NOBODY READS "DONE" AS "BRIDGE 1 IS PORTED":
# de-severing `run_v1(sdsc: &mut SuperDsc, sites: &mut P, ..)` (ddc/v1.rs:6532) back to the ONE
# object the reference mutates, and DELETING schedule/stages/{ddc_store,ddc_store2,ddc_state,
# ddc_sites,ddc_tree,ddc_reads,offsets,env}.rs. That is the acceptance test (see
# crustify-types/scope-config.json's _comment_acceptance) and it CANNOT be scheduled from this
# campaign's oracle target: `Ddc::run_v1` lives in ddc/ddcv1.cpp, which is not in the `dsc` target's
# impl_files. It needs the types to land FIRST, then its own campaign over ddc/.
say "NEXT, AND NOT DONE HERE: de-sever run_v1 to one &mut SuperDsc and DELETE the eight carrier files"
