#loc = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":103:1)
#loc11 = loc("desc_ids"(#loc))
#loc12 = loc("desc_table"(#loc))
#loc13 = loc("desc_o"(#loc))
module {
  tt.func public @embedding_fwd(%desc_ids: !tt.ptr<i32> loc("desc_ids"(#loc)), %desc_table: !tt.ptr<f16> loc("desc_table"(#loc)), %desc_o: !tt.ptr<f16> loc("desc_o"(#loc))) attributes {noinline = false} {
    %cst = arith.constant dense<1.200000e+01> : tensor<64x128xf16> loc(#loc1)
    %c0_i32 = arith.constant 0 : i32 loc(#loc2)
    %c64_i32 = arith.constant 64 : i32 loc(#loc2)
    %c128_i64 = arith.constant 128 : i64 loc(#loc2)
    %c128_i32 = arith.constant 128 : i32 loc(#loc2)
    %table_desc = arith.constant 512 : i32 loc(#loc14)
    %c1_i64 = arith.constant 1 : i64 loc(#loc2)
    %c256_i32 = arith.constant 256 : i32 loc(#loc2)
    %start_m = tt.get_program_id x : i32 loc(#loc15)
    %ids_desc = tt.make_tensor_descriptor %desc_ids, [%c256_i32], [%c1_i64] : <i32>, <64xsi32> loc(#loc16)
    %table_desc_0 = tt.make_tensor_descriptor %desc_table, [%table_desc, %c128_i32], [%c128_i64, %c1_i64] : <f16>, <1x128xf16> loc(#loc14)
    %o_desc = tt.make_tensor_descriptor %desc_o, [%c256_i32, %c128_i32], [%c128_i64, %c1_i64] : <f16>, <64x128xf16> loc(#loc17)
    %offs_m = arith.muli %start_m, %c64_i32 : i32 loc(#loc18)
    %ids = tt.descriptor_load %ids_desc[%offs_m] : !tt.tensordesc<64xsi32> -> tensor<64xi32> loc(#loc19)
    %rows = tt.descriptor_gather %table_desc_0[%ids, %c0_i32] : (!tt.tensordesc<1x128xf16>, tensor<64xi32>, i32) -> tensor<64x128xf16> loc(#loc20)
    %0 = arith.mulf %rows, %cst : tensor<64x128xf16> loc(#loc1)
    tt.descriptor_store %o_desc[%offs_m, %c0_i32], %0 : !tt.tensordesc<64x128xf16>, tensor<64x128xf16> loc(#loc10)
    tt.return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":129:31)
#loc2 = loc(unknown)
#loc3 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":115:18)
#loc4 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":109:15)
#loc5 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":112:16)
#loc6 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":118:14)
#loc7 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":122:14)
#loc8 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":123:11)
#loc9 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":126:12)
#loc10 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/embedding.py":129:5)
#loc14 = loc("table_desc"(#loc3))
#loc15 = loc("start_m"(#loc4))
#loc16 = loc("ids_desc"(#loc5))
#loc17 = loc("o_desc"(#loc6))
#loc18 = loc("offs_m"(#loc7))
#loc19 = loc("ids"(#loc8))
#loc20 = loc("rows"(#loc9))
