#loc = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":42:1)
#loc11 = loc("a_ptr"(#loc))
#loc12 = loc("b_ptr"(#loc))
#loc13 = loc("c_ptr"(#loc))
#loc14 = loc("n"(#loc))
module {
  tt.func public @mul_kernel(%a_ptr: !tt.ptr<f16> loc("a_ptr"(#loc)), %b_ptr: !tt.ptr<f16> loc("b_ptr"(#loc)), %c_ptr: !tt.ptr<f16> loc("c_ptr"(#loc)), %n: i32 loc("n"(#loc))) attributes {noinline = false} {
    %c1_i64 = arith.constant 1 : i64 loc(#loc1)
    %c64_i32 = arith.constant 64 : i32 loc(#loc1)
    %pid = tt.get_program_id x : i32 loc(#loc15)
    %offset = arith.muli %pid, %c64_i32 : i32 loc(#loc16)
    %a_desc = tt.make_tensor_descriptor %a_ptr, [%n], [%c1_i64] : <f16>, <64xf16> loc(#loc17)
    %b_desc = tt.make_tensor_descriptor %b_ptr, [%n], [%c1_i64] : <f16>, <64xf16> loc(#loc18)
    %c_desc = tt.make_tensor_descriptor %c_ptr, [%n], [%c1_i64] : <f16>, <64xf16> loc(#loc19)
    %a = tt.descriptor_load %a_desc[%offset] : !tt.tensordesc<64xf16> -> tensor<64xf16> loc(#loc20)
    %b = tt.descriptor_load %b_desc[%offset] : !tt.tensordesc<64xf16> -> tensor<64xf16> loc(#loc21)
    %0 = arith.mulf %a, %b : tensor<64xf16> loc(#loc9)
    tt.descriptor_store %c_desc[%offset], %0 : !tt.tensordesc<64xf16>, tensor<64xf16> loc(#loc10)
    tt.return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":43:11)
#loc3 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":44:14)
#loc4 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":45:14)
#loc5 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":47:14)
#loc6 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":49:14)
#loc7 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":51:9)
#loc8 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":52:9)
#loc9 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":53:28)
#loc10 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":53:5)
#loc15 = loc("pid"(#loc2))
#loc16 = loc("offset"(#loc3))
#loc17 = loc("a_desc"(#loc4))
#loc18 = loc("b_desc"(#loc5))
#loc19 = loc("c_desc"(#loc6))
#loc20 = loc("a"(#loc7))
#loc21 = loc("b"(#loc8))
