#loc = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":42:1)
#loc10 = loc("a_ptr"(#loc))
#loc11 = loc("b_ptr"(#loc))
#loc12 = loc("c_ptr"(#loc))
#loc13 = loc("n"(#loc))
module {
  tt.func public @mul_kernel(%a_ptr: !tt.ptr<f16> loc("a_ptr"(#loc)), %b_ptr: !tt.ptr<f16> loc("b_ptr"(#loc)), %c_ptr: !tt.ptr<f16> loc("c_ptr"(#loc)), %n: i32 loc("n"(#loc))) attributes {noinline = false} {
    %pid = tt.get_program_id x : i32 loc(#loc14)
    %offset = arith.constant 64 : i32 loc(#loc15)
    %offset_0 = arith.constant 64 : i32 loc(#loc15)
    %offset_1 = arith.extsi %pid : i32 to i64 loc(#loc15)
    %offset_2 = arith.extsi %offset_0 : i32 to i64 loc(#loc15)
    %offset_3 = arith.muli %offset_1, %offset_2 : i64 loc(#loc15)
    %offset_4 = arith.constant 2147483647 : i64 loc(#loc15)
    %offset_5 = arith.constant -2147483648 : i64 loc(#loc15)
    %offset_6 = arith.cmpi sle, %offset_3, %offset_4 : i64 loc(#loc15)
    %offset_7 = arith.cmpi sge, %offset_3, %offset_5 : i64 loc(#loc15)
    %offset_8 = arith.andi %offset_6, %offset_7 : i1 loc(#loc15)
    %offset_9 = arith.muli %pid, %offset_0 : i32 loc(#loc15)
    %a_desc = arith.constant 1 : i64 loc(#loc16)
    %a_desc_10 = tt.make_tensor_descriptor %a_ptr, [%n], [%a_desc] : <f16>, <64xf16> loc(#loc16)
    %b_desc = arith.constant 1 : i64 loc(#loc17)
    %b_desc_11 = tt.make_tensor_descriptor %b_ptr, [%n], [%b_desc] : <f16>, <64xf16> loc(#loc17)
    %c_desc = arith.constant 1 : i64 loc(#loc18)
    %c_desc_12 = tt.make_tensor_descriptor %c_ptr, [%n], [%c_desc] : <f16>, <64xf16> loc(#loc18)
    %a = tt.descriptor_load %a_desc_10[%offset_9] : !tt.tensordesc<64xf16> -> tensor<64xf16> loc(#loc19)
    %b = tt.descriptor_load %b_desc_11[%offset_9] : !tt.tensordesc<64xf16> -> tensor<64xf16> loc(#loc20)
    %0 = arith.mulf %a, %b : tensor<64xf16> loc(#loc8)
    tt.descriptor_store %c_desc_12[%offset_9], %0 : !tt.tensordesc<64xf16>, tensor<64xf16> loc(#loc9)
    tt.return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":43:11)
#loc2 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":44:14)
#loc3 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":45:14)
#loc4 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":47:14)
#loc5 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":49:14)
#loc6 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":51:9)
#loc7 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":52:9)
#loc8 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":53:28)
#loc9 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/mul.py":53:5)
#loc14 = loc("pid"(#loc1))
#loc15 = loc("offset"(#loc2))
#loc16 = loc("a_desc"(#loc3))
#loc17 = loc("b_desc"(#loc4))
#loc18 = loc("c_desc"(#loc5))
#loc19 = loc("a"(#loc6))
#loc20 = loc("b"(#loc7))
