#loc = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":234:1)
#loc19 = loc("desc_x"(#loc))
#loc20 = loc("desc_cos"(#loc))
#loc21 = loc("desc_sin"(#loc))
#loc22 = loc("desc_o"(#loc))
module {
  tt.func public @rope_fwd(%desc_x: !tt.ptr<f16> loc("desc_x"(#loc)), %desc_cos: !tt.ptr<f16> loc("desc_cos"(#loc)), %desc_sin: !tt.ptr<f16> loc("desc_sin"(#loc)), %desc_o: !tt.ptr<f16> loc("desc_o"(#loc))) attributes {noinline = false} {
    %c64_i32 = arith.constant 64 : i32 loc(#loc1)
    %c0_i32 = arith.constant 0 : i32 loc(#loc1)
    %c8_i32 = arith.constant 8 : i32 loc(#loc1)
    %c1_i64 = arith.constant 1 : i64 loc(#loc1)
    %c128_i64 = arith.constant 128 : i64 loc(#loc1)
    %c128_i32 = arith.constant 128 : i32 loc(#loc1)
    %y_dim = arith.constant 2048 : i32 loc(#loc23)
    %pos = tt.get_program_id x : i32 loc(#loc24)
    %x_desc = tt.make_tensor_descriptor %desc_x, [%y_dim, %c128_i32], [%c128_i64, %c1_i64] : <f16>, <8x64xf16> loc(#loc25)
    %cos_desc = tt.make_tensor_descriptor %desc_cos, [%y_dim, %c128_i32], [%c128_i64, %c1_i64] : <f16>, <8x64xf16> loc(#loc26)
    %sin_desc = tt.make_tensor_descriptor %desc_sin, [%y_dim, %c128_i32], [%c128_i64, %c1_i64] : <f16>, <8x64xf16> loc(#loc27)
    %o_desc = tt.make_tensor_descriptor %desc_o, [%y_dim, %c128_i32], [%c128_i64, %c1_i64] : <f16>, <8x64xf16> loc(#loc28)
    %offs_m = arith.muli %pos, %c8_i32 : i32 loc(#loc29)
    %x1 = tt.descriptor_load %x_desc[%offs_m, %c0_i32] : !tt.tensordesc<8x64xf16> -> tensor<8x64xf16> loc(#loc30)
    %x2 = tt.descriptor_load %x_desc[%offs_m, %c64_i32] : !tt.tensordesc<8x64xf16> -> tensor<8x64xf16> loc(#loc31)
    %c = tt.descriptor_load %cos_desc[%offs_m, %c0_i32] : !tt.tensordesc<8x64xf16> -> tensor<8x64xf16> loc(#loc32)
    %s = tt.descriptor_load %sin_desc[%offs_m, %c0_i32] : !tt.tensordesc<8x64xf16> -> tensor<8x64xf16> loc(#loc33)
    %0 = arith.mulf %x1, %c : tensor<8x64xf16> loc(#loc13)
    %1 = arith.mulf %x2, %s : tensor<8x64xf16> loc(#loc14)
    %2 = arith.subf %0, %1 : tensor<8x64xf16> loc(#loc13)
    tt.descriptor_store %o_desc[%offs_m, %c0_i32], %2 : !tt.tensordesc<8x64xf16>, tensor<8x64xf16> loc(#loc15)
    %3 = arith.mulf %x2, %c : tensor<8x64xf16> loc(#loc16)
    %4 = arith.mulf %x1, %s : tensor<8x64xf16> loc(#loc17)
    %5 = arith.addf %3, %4 : tensor<8x64xf16> loc(#loc16)
    tt.descriptor_store %o_desc[%offs_m, %c64_i32], %5 : !tt.tensordesc<8x64xf16>, tensor<8x64xf16> loc(#loc18)
    tt.return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":244:5)
#loc3 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":243:11)
#loc4 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":248:14)
#loc5 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":262:16)
#loc6 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":265:16)
#loc7 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":268:14)
#loc8 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":275:14)
#loc9 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":277:10)
#loc10 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":278:10)
#loc11 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":281:9)
#loc12 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":282:9)
#loc13 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":285:31)
#loc14 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":285:40)
#loc15 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":285:5)
#loc16 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":286:34)
#loc17 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":286:43)
#loc18 = loc("/Users/nickm/git/triton-spyre/.claude/worktrees/paged-attn-lowering/third_party/spyre/test/fixtures/rope.py":286:5)
#loc23 = loc("y_dim"(#loc2))
#loc24 = loc("pos"(#loc3))
#loc25 = loc("x_desc"(#loc4))
#loc26 = loc("cos_desc"(#loc5))
#loc27 = loc("sin_desc"(#loc6))
#loc28 = loc("o_desc"(#loc7))
#loc29 = loc("offs_m"(#loc8))
#loc30 = loc("x1"(#loc9))
#loc31 = loc("x2"(#loc10))
#loc32 = loc("c"(#loc11))
#loc33 = loc("s"(#loc12))
